[package]
name = "image-sorter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
clap = { version = "4.5.19", features = ["derive"] }
itertools = "0.12.1"
kamadak-exif = "0.5.5"
